GET http://localhost:5069/posts

####

POST http://localhost:5069/posts
Content-Type: application/json

{
    "category": "Referencing",
    "title": "Post con referencing",
    "cover": "immagine.jpeg",
    "readTime": {
        "value": 2,
        "unit": "minutes"
    },
    "author": "64baad4c869881bd816d0f85",
    "content": "Ciao sono marciellooooooooo"
}

####

GET http://localhost:5069/posts/title?postTitle=refe


####