GET http://localhost:5069/posts

####

POST http://localhost:5069/posts
Content-Type: application/json

{
    "category": "horror",
    "title": "Titolo post 21",
    "cover": "immagine.jpeg",
    "readTime": {
        "value": 2,
        "unit": "minutes"
    },
    "author": {
        "name": "Marcello",
        "avatar": "Mistiko"
    },
    "content": "Ciao sono marciellooooooooo"
}

####

GET http://localhost:5069/posts/title?postTitle=21


####