GET http://localhost:5069/posts

####

POST http://localhost:5069/posts/create
Content-Type: application/json

{
    "category": "Referencing 3",
    "title": "Post con referencing terzo test",
    "cover": "immagine.jpeg",
    "readTime": {
        "value": 5,
        "unit": "seconds"
    },
    "author": "64bac6cfc811ace5c3535d66",
    "content": "scemochilegge kekw (ma più lungo altrimenti va in errore hahaha)"
}

####

GET http://localhost:5069/posts/title?postTitle=refe


####